language: node_js
node_js:
- '0.10'
before_script:
- npm install -g grunt-cli
env:
  global:
  - secure: fBIU1iMb48IYCLneFT5TjVNxTF4YOSf4HmJlwRyaFGPq+7hKtYF5Osx9zkd6sDGwSEySNhUtgFWcUSxCrxrd37s1UcA3tGsLIQKYmJ2gED6txleN85D3eLene2U+wHceTEVW97gGQ5LTEdvNBWZzplZychLg1IoHdcJLdbbuD/0=
  - secure: DqreZxwvnny7LIc6pEwQapdoEwA8TqXMOkvdhpEtT80hmNkONx/+IqFJ0XmIn7G6EYKc7+V9XpWIQHjytHX7nNzRIPTq1tStIlKhgwmoIZxt2iWsOB3Axie1MYxH5DQnCHzF5LC9gEFSqV1hQnBVWs4rx4t284dJjB7DqK6eYZA=
